version: '3.9'

volumes:
  logs:
    external: true

services:

  statistics:
    image: docker22de/statistics:1.0
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      TOPIC: ${TOPIC}
    volumes:
      - logs:/app/logs


networks:
  default:
    name: kafka_default

